name: Build

on:
  pull_request: ~
  push: ~

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Validate composer.json
        run: composer validate --strict --no-check-lock
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
#          - description: 'Symfony 7.1 DEV'
#            php: '8.2'
#            symfony: '7.1.*@dev'
          - description: 'Symfony 7.0'
            php: '8.3'
            symfony: '7.0.*'
          - description: 'Symfony 6.4'
            php: '8.1'
            symfony: '6.4.*'
#          - description: 'Beta deps'
#            php: '8.1'
#            beta: true
    name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: composer-${{ matrix.php }}-${{ matrix.symfony }}-${{ matrix.composer_option }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: |
          sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'${{ matrix.symfony }}'"/' composer.json;
        if: matrix.symfony
      - run: |
          composer config minimum-stability dev
          composer config prefer-stable true
        if: matrix.beta
      - run: composer update --prefer-dist --no-interaction --no-progress --ansi ${{ matrix.composer_option }}
#      - run: vendor/bin/phpunit
