name: bundle-CI
on:
  [push, pull_request]
jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Checkout
        uses: actions/checkout@v4
      - name: composer install
        run: composer install
      - name: PHPStan
        run: composer phpstan
        env:
          REQUIRE_DEV: true
#  cs-fixer:
#    runs-on: ubuntu-latest
#    name: PHP-CS-Fixer
#    steps:
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.2
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: composer install
#        run: composer install
##      - name: CS Check
##        run: composer cs-check
  tests:
    name: PHP ${{ matrix.php }} / SF ^${{ matrix.symfony }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          include:
#            - description: 'Symfony 7.2 RC'
#              php: '8.3'
#              symfony: '7.2.*'
#              rc: true
            - description: 'Symfony 7.1'
              php: '8.3'
              symfony: '7.1.*'
            - description: 'Symfony 6.4'
              php: '8.3'
              symfony: '6.4.*'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Setup MySQL
#        run: |
#          sudo systemctl enable mysql.service
#          sudo systemctl start mysql.service
#          mysql -uroot -proot -h localhost -e "CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: |
          sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "${{ matrix.symfony }}"/' composer.json;
      - run: composer update --no-interaction --no-progress --ansi
      - run: composer phpunit
      -
        if: matrix.rc
        run: |
          composer config minimum-stability RC
          composer config prefer-stable true
      -
        if: matrix.beta
        run: |
          composer config minimum-stability beta
          composer config prefer-stable true
